--- 
framework: jest
postMerge: 
  pattern: 
    - src/**/*.test.js
postRun: 
  command: 
    - "node --version"
  env:
    BABEL_ENV: test
preMerge: 
  pattern: 
    - src/**/*.test.js
preRun: 
  command: 
    - "npm install"

